  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082" # FOR DOCKER 
    volumes:
      - nexus-data:/nexus-data
    restart: always

  volumes:
     nexus-data:
